<link rel="stylesheet" href="css/bootstrap.min.css" />
<link rel="stylesheet" href="css/font-awesome.min.css" />
<link rel="stylesheet" href="css/flaticon.css" />
<link rel="stylesheet" href="css/owl.carousel.min.css" />
<link rel="stylesheet" href="css/owl.theme.css" />
<link rel="stylesheet" href="css/magnific-popup.css" />
<link rel="stylesheet" href="css/style.css" />
<link rel="stylesheet" href="css/royal-preload.css" />
<link rel="stylesheet" type="text/css" href="plugins/revolution/revolution/css/settings.css">   
<link rel="stylesheet" type="text/css" href="plugins/revolution/revolution/css/navigation.css">